import type { Product } from '@/types/productType';

export const PRODUCTS_DATA: Product[] = [
  {
    id: '1',
    slug: 'monocrystalline-solar-panels',
    name: 'Monocrystalline Solar Panels',
    sku: 'SP-MONO-550W',
    category: 'SOLAR_PANEL',
    brand: 'Longi',
    status: 'ACTIVE',
    imageUrl: '/assets/images/solar-panels.svg',
    powerW: 550,
    efficiency: '22.4%',
    warranty: '3 Years',
    type: 'Mono',
  },
  {
    id: '2',
    slug: 'solar-inverters',
    name: 'Solar Inverters',
    sku: 'INV-HYB-5000',
    category: 'INVERTER',
    brand: 'Growatt',
    status: 'ACTIVE',
    imageUrl: '/assets/images/solar-inverters.svg',
    powerW: 5000,
    efficiency: '97%',
    warranty: '5 Years',
    type: 'Hybrid',
  },
  {
    id: '3',
    slug: 'lifepo4-battery',
    name: 'LiFePO4 Battery',
    sku: 'BAT-LFP-5KWH',
    category: 'BATTERY',
    brand: 'Felicity',
    status: 'ACTIVE',
    imageUrl: '/assets/images/solar-batteries.svg',
    powerW: 500,
    efficiency: '95%',
    warranty: '10 Years',
    type: 'LiFePO4',
  },
  {
    id: '4',
    slug: 'polycrystalline-solar-panels',
    name: 'Polycrystalline Solar Panels',
    sku: 'SP-POLY-450W',
    category: 'SOLAR_PANEL',
    brand: 'Jinko',
    status: 'ACTIVE',
    imageUrl: '/assets/images/Polycrystalline-Solar-Panels.svg',
    powerW: 450,
    efficiency: '18.5%',
    warranty: '2 Years',
    type: 'Poly',
  },
];

export const products = [
  {
    id: 1,
    title: '5kW Hybrid Inverter',
    subtitle: 'Smart Energy Management',
    image: '/assets/images/related-product-1.png',
  },
  {
    id: 2,
    title: '10kWh Lithium Battery',
    subtitle: 'Long-Cycle Energy Storage',
    image: '/assets/images/related-product-2.png',
  },
  {
    id: 3,
    title: '400W Residential Panel',
    subtitle: 'Compact & High Performance',
    image: '/assets/images/related-product-3.png',
  },
  {
    id: 4,
    title: 'Universal Mounting Kit',
    subtitle: 'For All Roof Types',
    image: '/assets/images/related-product-4.png',
  },
];
